// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_folio.data;

namespace e_folio.data.Migrations
{
    [DbContext(typeof(eFolioDBContext))]
    [Migration("20190220111820_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("e_folio.core.Entities.ClientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<string>("FullNameClient");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("e_folio.core.Entities.ContactPersonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientEntityId");

                    b.Property<string>("Comment");

                    b.Property<string>("FullName");

                    b.Property<int>("Phone");

                    b.Property<string>("eMail");

                    b.HasKey("Id");

                    b.HasIndex("ClientEntityId");

                    b.ToTable("ContactPersons");
                });

            modelBuilder.Entity("e_folio.core.Entities.ContextEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SourceCodeLink");

                    b.HasKey("Id");

                    b.ToTable("Contexsts");
                });

            modelBuilder.Entity("e_folio.core.Entities.DeveloperEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CVLink");

                    b.Property<string>("FullName");

                    b.HasKey("Id");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("e_folio.core.Entities.FolioFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContextEntityId");

                    b.Property<bool>("IsInternal");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.HasIndex("ContextEntityId");

                    b.ToTable("FolioFiles");
                });

            modelBuilder.Entity("e_folio.core.Entities.ProjectDeveloperEntity", b =>
                {
                    b.Property<int>("ProjectId");

                    b.Property<int>("DeveloperId");

                    b.HasKey("ProjectId", "DeveloperId");

                    b.HasIndex("DeveloperId");

                    b.ToTable("ProjectDeveloperEntity");
                });

            modelBuilder.Entity("e_folio.core.Entities.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContextId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ContextId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("e_folio.core.Entities.ContactPersonEntity", b =>
                {
                    b.HasOne("e_folio.core.Entities.ClientEntity")
                        .WithMany("ContactPersons")
                        .HasForeignKey("ClientEntityId");
                });

            modelBuilder.Entity("e_folio.core.Entities.FolioFileEntity", b =>
                {
                    b.HasOne("e_folio.core.Entities.ContextEntity")
                        .WithMany("ScreenLinks")
                        .HasForeignKey("ContextEntityId");
                });

            modelBuilder.Entity("e_folio.core.Entities.ProjectDeveloperEntity", b =>
                {
                    b.HasOne("e_folio.core.Entities.DeveloperEntity", "DeveloperEntity")
                        .WithMany("Projects")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("e_folio.core.Entities.ProjectEntity", "ProjectEntity")
                        .WithMany("Developers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("e_folio.core.Entities.ProjectEntity", b =>
                {
                    b.HasOne("e_folio.core.Entities.ContextEntity", "Context")
                        .WithMany()
                        .HasForeignKey("ContextId");
                });
#pragma warning restore 612, 618
        }
    }
}
